apiVersion: v2
name: lnx-adsagent
description: A Helm chart to run ads agent in Kubernetes

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.1

# This is the version number of the application.
# It is used as the tag name of the agent image
appVersion: v1.0.2
